project_id = "oiawdxbwnfupwajxfdcp"

[functions.send-notification]
verify_jwt = true

[functions.run-scheduled-tests]
verify_jwt = false

[functions.export-study-data]
verify_jwt = true

[functions.collect-aws-evidence]
verify_jwt = false

[functions.collect-okta-evidence]
verify_jwt = false

[functions.collect-azure-evidence]
verify_jwt = false

[functions.seed-prp-data]
verify_jwt = true

[functions.detect-anomalies]
verify_jwt = false